### ISSUE TITLE
Safely rescue Errno::EPIPE exceptions

### ISSUE THREAD

**Issue by postmodern** [dry-rb/dry-cli#102]
When a ruby program is piped into `| less` and `less` is exited before the ruby program can exit, Ruby will raise a `Errno::EPIPE` exception when stdio is accessed, causing an ugly backtrace to be printed. `Dry::CLI` should rescue the `Errno::EPIPE` exception and safely exit, calling any additional cleanup blocks/methods, with status code 0.

### Without `rescue Errno::EPIPE`

```ruby
begin
  (0..Float::INFINITY).each do |i|
    $stdout.puts i
    $stdout.flush
  end
rescue Interrupt
  exit 130
end
```

```
$ ruby test.rb | less
q
Traceback (most recent call last):
	3: from ./test.rb:4:in `<main>'
	2: from ./test.rb:4:in `each'
	1: from ./test.rb:6:in `block in <main>'
./test.rb:6:in `flush': Broken pipe (Errno::EPIPE)
$ 
```

### With `rescue Errno::EPIPE`

```ruby
begin
  (0..Float::INFINITY).each do |i|
    $stdout.puts i
    $stdout.flush
  end
rescue Interrupt
  exit 130
rescue Errno::EPIPE
end
```

```
$ ruby test.rb | less
q
$
```

**Comment by IvanShamatov** [comment]
Will be merged with #111
