### ISSUE TITLE
Documentation Page Commands with Subcommands and Params Downloads instead of Opens

### ISSUE THREAD

**Issue by RomanTurner** [dry-rb/dry-cli#124]
## Describe the bug

When accessing [Commands with subcommands and params](https://dry-rb.org/gems/dry-cli/1.0/commands-with-subcommands-and-params) in the documentation, it downloads a source file instead of displaying the page in the browser. 

https://user-images.githubusercontent.com/74572905/216214079-b4382c56-1740-4e00-99ad-b0af426d7c4d.mov

## To Reproduce

Click on the link above.

**Comment by CKolkey** [comment]
Same issue.
