### ISSUE TITLE
Auto complete subcommands using <tab>

### ISSUE THREAD

**Issue by mkarklinsScout** [dry-rb/dry-cli#39]
Had there been an idea of sub-command autocompletion feature? If thats not on the roadmap, I could probably take a stab at that.

**Comment by davydovanton** [comment]
Hey, good suggestion I love it. Do you have any ideas how to make it?

**Comment by cllns** [comment]
Based on a cursory search, it seems like there might not be a good way to do this. :/ 
https://stackoverflow.com/questions/11625229/can-a-gem-binary-bring-its-own-tab-completion

**Comment by mkarklinsScout** [comment]
Yes, looks like there isn't a very _ruby_ way of doing it, so probably the effort for introducing and supporting different flavors of shell to accomplish this task, outweighs the benefits.

**Comment by AlfonsoUceda** [comment]
Hi folks, I think this should be done with bash, in my company we have a bash binary for our commands (we aren't using hanami cli, just our custom CLI) but I don't know if we should provide that.

**Comment by IvanShamatov** [comment]
Closing this one as outdated and @davydovanton unassigned himself from implementing this.

**Comment by rngtng** [comment]
FYI I build a little gem to bring this feature to dry-cli: https://rubygems.org/gems/dry-cli-completion

More infos see:
https://www.rngtng.com/2022/12/08/enable-tab-completion-dry-cli.html
