### ISSUE TITLE
Allow disabling --no-* in boolean arguments

### ISSUE THREAD

**Issue by d4rky-pl** [dry-rb/dry-cli#42]
Always adding `--no-*` makes arguments like `--skip-something`  use double-negative (`--no-skip-something`) and it might not make sense in all contexts

**Comment by AlfonsoUceda** [comment]
@d4rky-pl I think that can be implemented of course but it has low priority IMO, if you wish to create a new PR for this feature, go ahead please ;)

**Comment by IvanShamatov** [comment]
@d4rky-pl Hi, is it still actual for your use cases or I can close this request?

**Comment by d4rky-pl** [comment]
@IvanShamatov it is but I also understand that it won't get implemented any time soon so it's fine to close this

**Comment by AviFS** [comment]
Just to clarify, this was thankfully added in the merged PR #117 above, and can be used with:

```rb
option :foo, type: flag
```

The use of `type: boolean` adds `--[no-]foo`, the use of `type: flag` adds only `--foo`.
