### ISSUE TITLE
Add ability to prompt for required options/arguments (feature request)

### ISSUE THREAD

**Issue by ianks** [dry-rb/dry-cli#53]
Oftentimes, it's tedious to find out which argument or option to pass. A nice feature would be to add the ability to use [tty-prompt](https://github.com/piotrmurach/tty-prompt) to select these options if they are not passed in. This would heavily improve the UX in my opinion.

**Comment by IvanShamatov** [comment]
As far as I remember, you can run a command without arguments and options, if you don't remember them, and your utility will return you an example with `usage` info.

**Comment by IvanShamatov** [comment]
It looks like it is a part of your application code, not a CLI framework. Very specific behaviour, in terms of formatting output, languages and colors, and can be easily implemented as a part of a command in case you really need it.
