### ISSUE TITLE
Inline command syntax

### ISSUE THREAD

**Issue by IvanShamatov** [dry-rb/dry-cli#63]
I would love to address the problem, that there is no way right now to create a single command executable. The easiest way for doing this IMO is to define DefaultCommand which will be called if there is nothing else in the `Registry`. 

But I'd love to suggest another approach. Let's think of the reasoning for using `dry-cli`. I believe that the developer is looking for some  gem to him drop-in syntax just to make a single command to do exactly one thing without many options. 

And I really like the way how `Sinatra` does it.

## Examples
*hellonamer*
```ruby
# /usr/bin/env ruby
require 'dry/cli/global'

argument :name, required: true, desc: "The name of the person to greet"
argument :age, desc: "The age of the person to greet"

run do |name:, age:|
  result = "Hello, #{name}."
  result = "#{result} You are #{age} years old." unless age.nil?

  puts result
end
```
And then just run

```bash
$ chmod +x hellonamer
$ ./hellonamer Homer
```

If that is not enough, you are still free to use all the features with a registry, subcommands and sub-subcommands, running `Dry::CLI::Core` instance

```ruby
require "dry/cli/core"
module Commands
  extend Dry::CLI::Registry

  class Hello < Dry::CLI::Command
    def call(*)
    end
  end
end

Commands.register "hi", Commands::Hello
Dry::CLI::Base.new(Foo::CLI::Commands).call
```

WDYT?

**Comment by solnic** [comment]
This is a good idea. Two things though:

- We could have `require "dry/cli/global"` to make it clearer that you require DSL that affects global namespace
- `Dry::CLI::Base` => `Dry::CLI::Core` because that's the naming convention we have in many places

**Comment by IvanShamatov** [comment]
https://github.com/dry-rb/dry-cli/pull/77
