### ISSUE TITLE
Showing default array option as a comma-separated list

### ISSUE THREAD

**Issue by janko** [dry-rb/dry-cli#81]
First of all, thank you everyone who participated in creating this tool. I'm using it now for the development of Shrine, the script automatizes setting up the S3 bucket with correct permissions. It's been a joy to use so far ❤️ 

Onto the issue. I have an array option (in my case `permissions`) which has a default value. When I print the page, the default value gets shown as a Ruby array:

```rb
module Commands
  class S3
    class Create < Dry::CLI::Command
      DEFAULT_PERMISSIONS = %w[
        GetObject
        PutObject
        PutObjectAcl
        DeleteObject
        ListMultipartUploadParts
        AbortMultipartUpload
      ]

      option :permissions, type: :array, default: DEFAULT_PERMISSIONS, desc: "list of S3 permissions"
      # ...
  end
end
```
```
$ shrine s3 create --help
Command:
  shrine s3 create

Usage:
  shrine s3 create

Options:
  --permissions=VALUE                   # list of S3 permissions, default: ["GetObject", "PutObject", "PutObjectAcl", "DeleteObject", "ListMultipartUploadParts", "AbortMultipartUpload"]
  ...
  --help, -h                            # Print this help
```

I think this might be a bit misleading, as the way to pass array arguments is via a comma-separated list. So, I think it would make sense that the default value is also displayed as a comma-separated list, to show the user how the input should look like.

**Comment by solnic** [comment]
That's a good suggestion. We could have default value "presenters", which would be `#to_s` by default and something special for more complex types where there's a mismatch between what you pass and how it's represented in Ruby.

**Comment by IvanShamatov** [comment]
@janko It is probably better to keep "default" representation as it is. Though, what can help to fix this misleading is to have VALUE to be a list. So that it will look like: 
```
Options:
  --permissions=VALUE1,VALUE2                   # list of S3 permissions, default: ["GetObject", "PutObject", "PutObjectAcl", "DeleteObject", "ListMultipartUploadParts", "AbortMultipartUpload"]
```

or even
```
Options:
  --permissions=VALUE,..             # list of S3 permissions, default: ["GetObject", "PutObject", "PutObjectAcl", "DeleteObject", "ListMultipartUploadParts", "AbortMultipartUpload"]
```

WDYT?

**Comment by IvanShamatov** [comment]
https://github.com/dry-rb/dry-cli/pull/84 PR for the solution I suggested
